### ISSUE TITLE
App crash on SettingsExampleActivity

### ISSUE THREAD

**Issue by anirudhd** [googlesamples/leanback-showcase#1] opened 2016-05-19 01:12 UTC
5-18 18:11:22.093 12591-12591/android.support.v17.leanback.supportleanbackshowcase E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                                      Process: android.support.v17.leanback.supportleanbackshowcase, PID: 12591
                                                                                                      java.lang.RuntimeException: Unable to start activity ComponentInfo{android.support.v17.leanback.supportleanbackshowcase/android.support.v17.leanback.supportleanbackshowcase.app.settings.SettingsExampleActivity}: java.lang.IllegalStateException: Must specify preferenceTheme in theme
                                                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2630)
                                                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2691)
                                                                                                          at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1444)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                                                          at android.app.ActivityThread.main(ActivityThread.java:6010)
                                                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:802)
                                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:692)
                                                                                                       Caused by: java.lang.IllegalStateException: Must specify preferenceTheme in theme
                                                                                                          at android.support.v14.preference.PreferenceFragment.onCreate(PreferenceFragment.java:218)
                                                                                                          at android.app.Fragment.performCreate(Fragment.java:2335)
                                                                                                          at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:949)
                                                                                                          at android.app.BackStackRecord.setLastIn(BackStackRecord.java:857)
                                                                                                          at android.app.BackStackRecord.calculateFragments(BackStackRecord.java:880)
                                                                                                          at android.app.BackStackRecord.run(BackStackRecord.java:727)
                                                                                                          at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1578)
                                                                                                          at android.app.Fragment.performStart(Fragment.java:2374)
                                                                                                          at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1027)
                                                                                                          at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
                                                                                                          at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153)
                                                                                                          at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2044)
                                                                                                          at android.app.FragmentController.dispatchStart(FragmentController.java:187)
                                                                                                          at android.app.Activity.performStart(Activity.java:6681)
                                                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2593)
                                                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2691) 
                                                                                                          at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1444) 
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                                          at android.os.Looper.loop(Looper.java:154) 
                                                                                                          at android.app.ActivityThread.main(ActivityThread.java:6010) 
                                                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:802) 
                                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:692)

**Comment by dakegu** [comment] 2016-05-19 04:12
This is a known issue caused by a build tools bug within Developer Preview 3,  we
should expect this being fixed in official N SDk.

**Comment by dakegu** [comment] 2016-06-18 00:09
fixed with latest update of SDK

**Comment by olicmoon** [comment] 2016-07-20 00:46
I didn't have problem until installing latest SDK. After installation, I'm having this issue

**Comment by dakegu** [comment] 2016-07-20 18:26
you are right,  it was fixed in previous release,  then reintroduced in last release of support library

**Comment by dakegu** [comment] 2016-08-23 20:05
verified in new release rev. 36

**Closed as completed by dakegu** 2016-08-23 20:05 UTC

**Comment by SehgalDivij** [comment] 2016-10-22 03:00
How do I solve this?
I haven't worked with Preference Activity before and I am not aware of the whole 'Preference Theme' thing.

**Comment by keyvanamiri** [comment] 2016-10-24 19:21
Could you please clarify if you're seeing a crash or you're just wondering what preferenceTheme is used for? Support library PreferenceFragments require you to define preferenceTheme. This attribute references a style which defines the look and layout of each one of the individual preferences and fragments. If you're installing this app on TV, we have a leanback-styled theme of @style/PreferenceThemeOverlay.v14.Leanback. If you take a look at "Theme.Example.LeanbackPreferences" you can see how it's defined there.
